<?php

use Illuminate\Database\Seeder;

class PruebaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('procesos')->insert([
            [
                'cod' => '002',
                'tipo_id' => '1',
                'nombre' => 'juan',
                'descripcion' => 'Ingeniero de sistemas',
                'n_plazas' => 20,
                'oficina' => '',
                'archivo_bases' => 'no detectado',
                'archivo_bases_tipo' => 'cv',
                'archivo_resolucion' => 'link',
                'archivo_resolucion_tipo' => 'link',
                'contrato_inicio' => '2019-03-13',
                'evaluar_conocimientos' => '5',
                'bon_ffaa' => '0.1',
                'bon_pers_disc' => '0.5',
                'bon_deport' => '0.5',
                'bon_otros1' => '0.5',
                'bon_otros2' => '0.5',
                'pje_otro' => '0.5',
                'pje_max_cv' => '0.5',
                'pje_min_cv' => '0.5',
                'pje_max_conoc' => '0.5',
                'pje_min_conoc' => '0.5',
                'pje_max_entrev' => '0.5',
                'pje_min_entrev' => '0.5',
                'anios_exp_lab_gen' => '0.5',
                'anios_exp_lab_esp' => '0.5',
                'horas_cap_ind' => '0.5',
                'fecha_aprobacion' => '2021-05-11',
                'fecha_publicacion' => '2021-06-12',
                'fecha_inscripcion_inicio' => '2021-06-13',
                'fecha_inscripcion_fin' => '2021-06-25',
                'fecha_resultados' => '2021-06-29',
                'archivo_preliminar' => 'dt',
                'archivo_preliminar_tipo' => 'th',
                'archivo_resultado' => 'fg',
                'archivo_resultado_tipo' => 'gh',                
            ],
         ]);
         DB::table('procesos')->insert([
            [
                'cod' => '002',
                'tipo_id' => '2',
                'nombre' => 'pedro ',
                'n_plazas' => 10,
                'descripcion' => 'prueba procesos 2',
                'oficina' => '',
                'archivo_bases' => 'no detectado',
                'archivo_bases_tipo' => 'cv',
                'archivo_resolucion' => 'liphpnk',
                'archivo_resolucion_tipo' => 'link',
                'contrato_inicio' => '2019-03-13',
                'evaluar_conocimientos' => '5',
                'bon_ffaa' => '0.1',
                'bon_pers_disc' => '0.5',
                'bon_deport' => '0.5',
                'bon_otros1' => '0.5',
                'bon_otros2' => '0.5',
                'pje_otro' => '0.5',
                'pje_max_cv' => '0.5',
                'pje_min_cv' => '0.5',
                'pje_max_conoc' => '0.5',
                'pje_min_conoc' => '0.5',
                'pje_max_entrev' => '0.5',
                'pje_min_entrev' => '0.5',
                'anios_exp_lab_gen' => '0.5',
                'anios_exp_lab_esp' => '0.5',
                'horas_cap_ind' => '0.5',
                'fecha_aprobacion' => '2021-05-11',
                'fecha_publicacion' => '2021-06-12',
                'fecha_inscripcion_inicio' => '2021-06-13',
                'fecha_inscripcion_fin' => '2021-06-28',
                'fecha_resultados' => '2021-06-29',
                'archivo_preliminar' => 'dt',
                'archivo_preliminar_tipo' => 'th',
                'archivo_resultado' => 'fg',
                'archivo_resultado_tipo' => 'gh',                
            ],
         ]);
         DB::table('procesos')->insert([
            [
                'cod' => '003',
                'tipo_id' => '3',
                'n_plazas' => 6,
                'nombre' => 'jonathan ',
                'descripcion' => 'Tecnico para el Aula virtual',
                'oficina' => '',
                'archivo_bases' => 'no detectado',
                'archivo_bases_tipo' => 'cv',
                'archivo_resolucion' => 'liphpnk',
                'archivo_resolucion_tipo' => 'link',
                'contrato_inicio' => '2019-03-13',
                'evaluar_conocimientos' => '5',
                'bon_ffaa' => '0.1',
                'bon_pers_disc' => '0.5',
                'bon_deport' => '0.5',
                'bon_otros1' => '0.5',
                'bon_otros2' => '0.5',
                'pje_otro' => '0.5',
                'pje_max_cv' => '0.5',
                'pje_min_cv' => '0.5',
                'pje_max_conoc' => '0.5',
                'pje_min_conoc' => '0.5',
                'pje_max_entrev' => '0.5',
                'pje_min_entrev' => '0.5',
                'anios_exp_lab_gen' => '0.5',
                'anios_exp_lab_esp' => '0.5',
                'horas_cap_ind' => '0.5',
                'fecha_aprobacion' => '2021-05-11',
                'fecha_publicacion' => '2021-06-12',
                'fecha_inscripcion_inicio' => '2021-06-10',
                'fecha_inscripcion_fin' => '2021-06-18',
                'fecha_resultados' => '2021-06-29',
                'archivo_preliminar' => 'dt',
                'archivo_preliminar_tipo' => 'th',
                'archivo_resultado' => 'fg',
                'archivo_resultado_tipo' => 'gh',                
            ],
         ]);              
    }
}
